/*
 Simegraph JS

 (c) 2015 Padrone

 License: www.padrone.nl/license
*/
window.simegraph=function(a,Q,f){function R(a,p,d){function m(a){var I=!1;if((125<g?c[a]<g:c[a]>g)||(125<h?c[++a]<h:c[++a]>h)||(125<k?c[++a]<k:c[++a]>k))I=!0;return I}function S(a){var I=!1;(125<g?c[a]>g:c[a]<g)&&(125<h?c[++a]>h:c[++a]<h)&&(125<k?c[++a]>k:c[++a]<k)&&(I=!0);return I}var e=0;d&&(e=d);d=Q[e];var e=J.width,f=J.height,r=T.width,u=T.height;b.fastDraw||K.drawImage(a,0,0);c&&b.fastDraw||(c=K.getImageData(0,0,r,u).data);D||(U=w.getImageData(0,0,e,f),D=U.data);a=e-1;var u=0,V=f-1,x=0,C=-1,
n=0,E=b.filterDepth,z=b.filterThreshold,l=4*E,t=4*r*E,g=parseInt(b.mask.substring(0,2),16),h=parseInt(b.mask.substring(2,4),16),k=parseInt(b.mask.substring(4,6),16);128<g?g-=b.jpgColorMargin:g+=b.jpgColorMargin;128<h?h-=b.jpgColorMargin:h+=b.jpgColorMargin;128<k?k-=b.jpgColorMargin:k+=b.jpgColorMargin;var F=e-d.dx;d.w<F&&(F=d.w);f=f-d.dy;d.h<f&&(f=d.h);for(var y=0;y<f;y++)for(var G=r*(y+d.y)*4+4*d.x,q=e*(y+0+d.dy)*4+4*(0+d.dx),H=n=0;H<F;H++,G+=4,q+=4){n<E&&m(G)&&n++;if(0<n){var v=G+l;H+E<d.w&&S(v)?
n-=2:(v=G-t,0<=v&&S(v)?n-=2:(v=G+t,y+E<d.h&&S(v)&&(n-=2)))}if(n>z){var v=G,A=q;D[A]=c[v];D[++A]=c[++v];D[++A]=c[++v]}b.e&&p&&(n>z?(-1==C&&(H<a&&(a=H),y<V&&(V=y)),C=1):-1!=C&&(H>u&&(u=H),y>x&&(x=y),C=-1))}w.putImageData(U,0,0);if(b.e&&p)return 0==u&&(u=d.w),0==x&&(x=d.h),{a:a,b:V,c:u,d:x,m:d.dx,n:d.dy,p:d.w,o:d.h}}function aa(a){var p,d=a.src.split("/");p=d[d.length-1];d=a.g;1==d&&console.log("var compCoordinates = [");for(var m=!1,c=0;c<W.length;c++)W[c]==p&&(m=!0);m||W.push(p);if(!m){a=R(a,!0);var e=
b.l,m=a.c-a.a+4*e,c=a.d-a.b+4*e;z+m>=r.width&&(z=0,L+=M,M=0);var q=z+e,t=L+e;p='  {name:"'+p+'", x:'+z+",y:"+L+",w:"+(a.c-a.a+4*e)+",h:"+(a.d-a.b+4*e)+", dx:"+(a.m+a.a-2*e)+", dy:"+(a.n+a.b-2*e)+"}";a.a-=e;a.c+=e;a.b-=e;a.d+=e;for(var e=J.width,u=r.width,l=r.height,x=K.getImageData(0,0,e,J.height).data,l=A.getImageData(0,0,u,l),C=l.data,n=parseInt(b.mask.substring(0,2),16),E=parseInt(b.mask.substring(2,4),16),D=parseInt(b.mask.substring(4,6),16),w,B,g,h=a.a;h<a.c;h++)for(var k=a.b;k<a.d;k++){g=e*
k*4+4*h;var F=u*(t+k-a.b)*4+4*(q+h-a.a);0>h||h>=a.p||0>k||k>=a.o?(w=128<n?0:255,B=128<E?0:255,g=128<D?0:255):(w=x[g],B=x[++g],g=x[++g]);C[F]=w;C[++F]=B;C[++F]=g}A.putImageData(l,0,0);p=d==f.length-1?p+"\n];":p+",";console.log(p);c>M&&(M=c);z+=m}}function ba(a){for(var b=Q.length,d=0,c=0;c<b&&!d;c++)Q[c].name==a&&(d=c);return d}function X(){var a=["webkit","moz","ms","o"];if("hidden"in document)return"hidden";for(var b=0;b<a.length;b++)if(a[b]+"Hidden"in document)return a[b]+"Hidden";return null}function N(){var a=
X();return a?document[a]:!1}function ca(){N()&&b.fastDraw&&w.drawImage(l,0,0)}function Y(){function a(c){function d(){c++;c<f.length?a(c):b.e||(b.loop?(c=1,a(c)):0<b.i&&(c=1,setTimeout(function(){a.call(O,c)},b.i+(N()?1E3:0))));if(b.fastDraw)N()||t(q,!1,ba(f[m].name));else{var d=Z[m];B[m]?t(d):(console.log("info: image not available yet, nr:"+m),B[m]=t)}}var m=c,l=b.frameSpeed;if(b.fastDraw){var e=f[m].time;e&&(l=e)}setTimeout(function(){d.call(O)},l+(N()?200:0))}a(1)}var b={mask:a&&a.mask?a.mask:
"00FF00",canvas:a&&a.canvas?a.canvas:"myCanvas",canvasVirtual:a&&a.canvasVirtual?a.canvasVirtual:"canvasVirtual",k:a&&a.compositeFile?a.compositeFile:"composite.jpg",j:a?a.basicDraw?!0:!1:!1,fastDraw:a?a.fastDraw?!0:!1:!1,e:a?a.compositeDraw?!0:!1:!1,addReverseJpgFiles:a?a.addReverseJpgFiles?!0:!1:!0,frameSpeed:a&&a.frameSpeed?a.frameSpeed:33,waitTimeStart:a&&a.waitTimeStart?a.waitTimeStart:3E3,i:a&&a.waitTimeRepeat?a.waitTimeRepeat:3E3,loop:a&&a.loop?a.loop:!1,jpgColorMargin:a&&a.jpgColorMargin?
a.jpgColorMargin:6,filterDepth:a&&a.filterDepth?a.filterDepth:10,filterThreshold:a&&a.filterThreshold?a.filterThreshold:6,l:a&&a.cutMargin?a.cutMargin:8,f:a&&a.path?a.path:"img/"},J=document.getElementById(b.canvas),w=J.getContext("2d"),T=document.getElementById(b.canvasVirtual),K=T.getContext("2d"),r,A,c=null,U=null,D=null,O=this,W=[],z=0,L=0,M=0;if(a=X())a=a.replace(/[H|h]idden/,"")+"visibilitychange",document.addEventListener(a,ca);if(b.addReverseJpgFiles)for(a=f.length-2;0<a;a--)f.push(f[a]);
var B=Array(f.length),t;b.j?t=R:b.e&&(t=aa,r=document.getElementById("compositeCanvas"),A=r.getContext("2d"),A.fillStyle="#"+b.mask,A.fillRect(0,0,r.width,r.height));var Z=[],l=new Image,q=new Image;if(b.fastDraw)t=R,l.onload=function(){w.drawImage(this,0,0);Date.now||(Date.now=function(){return(new Date).getTime()});var a=Date.now();q.onload=function(){var c=b.waitTimeStart+a-Date.now();1>c&&(c=1);setTimeout(function(){K.drawImage(q,0,0);Y.call(O)},c)};q.src=b.f+b.k;},l.src=b.f+f[0].name;else for(a=0;a<f.length;a++){var P=new Image;P.src=b.f+f[a].name;P.g=a;Z.push(P);P.onload=0==a?function(){w.drawImage(this,0,0);setTimeout(function(){Y.call(O)},b.waitTimeStart)}:function(){var a=this.g;if(0<=a)if(B[a])B[a](l[a]);else B[a]=!0}}};